#!/usr/bin/env python3
"""
gen_synth_v4.py — synthetic corpus where the PLAN is an executable, parameterized program.

Why this exists: the v3 corpus collapsed to 7 distinct plans / 1000 rows because plan
primitives were vague meta-labels (GENERATE_ALT, EVAL, ...) with no parameters and no
execution semantics, so I(plan; answer | instruction) ≈ 0 and no plan-conditioning could
be learned. Here a plan is a sequence of (OP, arg) steps over an accumulator machine and
  answer == execute(plan)
so the mutual information is maximal by construction. Because plans are executable we get an
ORACLE: a hard negative is generated by perturbing one step, RE-EXECUTING, and keeping it only
if the answer genuinely changes (and differs from the other negatives). Primitives are reused
across every schema and behave differently purely through their parameter — MUL 5 vs MUL 7.

Output row schema (drop-in for the existing pipeline + checkers.py):
  {id, category, instruction, plan:[[op,arg],...], plan_str, answer,
   hard_negatives:[{plan, plan_str, answer}, x3],
   checker_kind:"numeric", checker_args:{canonical:{value}, match:{tolerance}}, reward_path}
"""
import json, os, random, argparse, itertools, collections

# --------------------------------------------------------------------------- interpreter
OPS = ["SET", "ADD", "SUB", "MUL", "DIV"]          # the reusable primitive vocabulary

def execute(plan):
    """Run an accumulator program. plan = [[op, arg], ...]; step 0 must be SET. Returns float
    or None if the program is ill-formed / divides by zero."""
    if not plan or plan[0][0] != "SET":
        return None
    acc = None
    for op, arg in plan:
        if op == "SET":   acc = float(arg)
        elif op == "ADD": acc += arg
        elif op == "SUB": acc -= arg
        elif op == "MUL": acc *= arg
        elif op == "DIV":
            if arg == 0: return None
            acc /= arg
        else: return None
    return acc

def fmt(x):
    """Round to 2dp, drop trailing zeros so 3450.0 -> '3450'."""
    if x is None: return None
    r = round(x + 0.0, 2)
    return str(int(r)) if r == int(r) else str(r)

def plan_str(plan):
    return " ".join(f"{op} {fmt(a)}" for op, a in plan)

# --------------------------------------------------------------------------- hard negatives
def candidate_negatives(plan, pool):
    """All single-edit perturbations of `plan`: op-swap at each step, operand-swap to any other
    number appearing in the problem, single-step drop (never the SET), and swap of two adjacent
    steps. The caller executes + filters these; we only enumerate plausible mistakes."""
    cands = []
    n = len(plan)
    for i in range(n):
        op, arg = plan[i]
        # op-swap (keep SET as SET; SET only changes via operand)
        if op != "SET":
            for alt in ("ADD", "SUB", "MUL", "DIV"):
                if alt != op:
                    cands.append(plan[:i] + [[alt, arg]] + plan[i+1:])
        # operand-swap: use a DIFFERENT number that actually appears in the problem
        for v in pool:
            if v != arg:
                cands.append(plan[:i] + [[op, v]] + plan[i+1:])
        # drop a non-SET step (forgot a step)
        if op != "SET" and n > 2:
            cands.append(plan[:i] + plan[i+1:])
    # swap two adjacent non-SET steps (order error; only bites non-commutative ops)
    for i in range(1, n-1):
        cands.append(plan[:i] + [plan[i+1], plan[i]] + plan[i+2:])
    return cands

def pick_hard_negatives(plan, pool, gold_ans, rng, k=3):
    """Return k executable plans whose answers are all distinct and != gold. Verified by the
    oracle, so every negative is a TRUE negative (answer genuinely changed)."""
    seen = {gold_ans}
    out = []
    cands = candidate_negatives(plan, pool)
    rng.shuffle(cands)
    for c in cands:
        a = execute(c)
        if a is None: continue
        key = fmt(a)
        if key in seen: continue              # distinct answer from gold AND other negatives
        seen.add(key)
        out.append((c, a))
        if len(out) == k: break
    return out

# --------------------------------------------------------------------------- schemas
# Each schema: sample numbers, build the NL instruction, the GOLD executable plan, and the pool
# of in-problem numbers used for operand-swap negatives. Primitives are shared across all schemas.
def s_profit(rng):
    E = rng.randint(8, 60); P = rng.randint(2, 12); S = rng.randint(10, 50); C = rng.randint(1, S-1)
    margin = S - C
    instr = (f"A workshop employs {E} workers. Each worker makes {P} units per day. "
             f"Every unit sells for ${S} and costs ${C} to make. What is the total daily profit?")
    plan = [["SET", E], ["MUL", P], ["MUL", margin]]
    return "arithmetic_profit", instr, plan, {E, P, S, C, margin}

def s_interest(rng):
    P = rng.randrange(200, 5000, 50); r = rng.choice([2,3,4,5,6,7,8,9,10,12]); t = rng.randint(2, 12); rf = r/100
    instr = (f"You invest ${P} at {r}% simple interest per year for {t} years. "
             f"How much interest do you earn in total?")
    plan = [["SET", P], ["MUL", rf], ["MUL", t]]
    return "simple_interest", instr, plan, {P, r, t, rf, P*rf}

def s_distance(rng):
    v = rng.randint(20, 90); t = rng.randint(2, 9)
    instr = f"A train travels at {v} km/h for {t} hours. How far does it go?"
    plan = [["SET", v], ["MUL", t]]
    return "distance_rate", instr, plan, {v, t}

def s_discount_tax(rng):
    p = rng.randrange(40, 400, 5); d = rng.choice([5,10,15,20,25,30,35,40]); x = rng.choice([4,5,6,7,8,9,10,12])
    df = (100-d)/100; xf = (100+x)/100
    instr = (f"A jacket is listed at ${p}. A {d}% discount is applied, then {x}% sales tax is added. "
             f"What is the final price?")
    plan = [["SET", p], ["MUL", round(df,4)], ["MUL", round(xf,4)]]
    return "discount_tax", instr, plan, {p, d, x, round(df,4), round(xf,4)}

def s_total_cost(rng):
    u = rng.randint(3, 60); up = rng.choice([3,4,5,6,7,8,9,10,12,15]); fee = rng.choice([5,8,10,12,15,20,25,30,40])
    instr = (f"You order {u} items at ${up} each, plus a flat ${fee} shipping fee. "
             f"What is the total cost?")
    plan = [["SET", u], ["MUL", up], ["ADD", fee]]
    return "linear_cost", instr, plan, {u, up, fee}

def s_work_rate(rng):
    r1 = rng.randint(2, 12); r2 = rng.randint(2, 12); units = rng.randint(2, 12)
    W = (r1 + r2) * units                         # choose W so time is clean
    cr = r1 + r2
    instr = (f"Pump A fills {r1} liters/min and pump B fills {r2} liters/min. Working together, "
             f"how many minutes to fill a {W}-liter tank?")
    plan = [["SET", W], ["DIV", cr]]
    return "work_rate", instr, plan, {r1, r2, W, cr}

def s_recipe(rng):
    a = rng.randint(2, 15); s = rng.randint(2, 20); k = rng.choice([2,3,4,5])   # k = unit conversion
    instr = (f"A recipe needs {a} grams of spice per serving. You cook {s} servings, and each gram "
             f"is {k} teaspoons. How many teaspoons of spice total?")
    plan = [["SET", a], ["MUL", s], ["MUL", k]]
    return "recipe_scaling", instr, plan, {a, s, k}

def s_savings(rng):
    I = rng.randrange(800, 6000, 50); spend = rng.randint(30, 80); kf = (100-spend)/100
    instr = (f"You earn ${I} a month and spend {spend}% of it. How much do you save each month?")
    plan = [["SET", I], ["MUL", round(kf,4)]]
    return "budget_savings", instr, plan, {I, spend, round(kf,4)}

SCHEMAS = [s_profit, s_interest, s_distance, s_discount_tax, s_total_cost, s_work_rate, s_recipe, s_savings]


def build_one_row(rng, seen_instr, idx, args):
    """One sampling attempt: returns a valid, deduped, oracle-verified row dict (and records its
    instruction in seen_instr), or None if this attempt is rejected."""
    schema = rng.choice(SCHEMAS)                          # random -> balanced, no exhaustion deadlock
    cat, instr, plan, pool = schema(rng)
    if instr in seen_instr:                               # dedupe identical instances
        return None
    gold = execute(plan)
    if gold is None:
        return None
    gold_f = fmt(gold)
    negs = pick_hard_negatives(plan, sorted(pool), gold_f, rng, k=args.k)
    if len(negs) < args.k:                                # demand k verified negatives
        return None
    seen_instr.add(instr)
    return {
        "id": f"syn_{idx:04d}",
        "category": cat,
        "instruction": instr,
        "plan": plan,
        "plan_str": plan_str(plan),
        "answer": gold_f,
        "hard_negatives": [
            {"plan": c, "plan_str": plan_str(c), "answer": fmt(a)} for c, a in negs],
        "checker_kind": "numeric",
        "checker_args": {"canonical": {"value": float(gold_f)}, "match": {"tolerance": 0.01}},
        "reward_path": "verifiable",
    }


def generate_batch(rng, seen_instr, per, n, start_idx, args):
    """Generate n valid rows, SHARING rng + seen_instr + per across calls (so a second batch is
    disjoint from the first by construction). Returns (rows, next_idx)."""
    batch, idx, attempts = [], start_idx, 0
    while len(batch) < n and attempts < n * 40:
        attempts += 1
        row = build_one_row(rng, seen_instr, idx, args)
        if row is None:
            continue
        per[row["category"]] += 1
        batch.append(row)
        idx += 1
    return batch, idx


# --------------------------------------------------------------------------- driver
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=1000)
    ap.add_argument("--k", type=int, default=3)
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--out", default="dataset/sft_synth_v4.jsonl")
    ap.add_argument("--val_n", type=int, default=0,
                    help="rows for a holdout VALIDATION set, generated AFTER the n training rows "
                         "from the SAME rng + seen_instr dedupe set (guaranteed disjoint).")
    ap.add_argument("--val_out", default="dataset/sft_synth_v4_val.jsonl")
    args = ap.parse_args()
    rng = random.Random(args.seed)

    seen_instr = set()
    per = collections.Counter()
    rows, idx = generate_batch(rng, seen_instr, per, args.n, 0, args)

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        for r in rows:
            f.write(json.dumps(r) + "\n")
    print(f"wrote {len(rows)} rows -> {args.out}")
    print("per-category:", dict(per))

    # holdout VALIDATION set: disjoint from train (shared seen_instr + continued rng), unique ids.
    if args.val_n > 0:
        os.makedirs(os.path.dirname(args.val_out), exist_ok=True)
        val_rows, idx = generate_batch(rng, seen_instr, per, args.val_n, idx, args)
        with open(args.val_out, "w") as f:
            for r in val_rows:
                f.write(json.dumps(r) + "\n")
        train_instr = {r["instruction"] for r in rows}
        val_instr = {r["instruction"] for r in val_rows}
        assert train_instr.isdisjoint(val_instr), "train/val instruction overlap!"
        print(f"wrote {len(val_rows)} VAL rows -> {args.val_out}  (disjoint from train, verified)")


if __name__ == "__main__":
    main()
